apiVersion: v1
kind: Service
metadata:
  name: crypto-service
spec:
  type: NodePort  # Change to LoadBalancer or NodePort if needed
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: crypto-service


######################################

# apiVersion: v1
# kind: Service
# metadata:
#   name: crypto-service
# spec:
#   selector:
#     app: crypto-service
#   ports:
#   - name: http
#     port: 80
#     targetPort: 5000
#   type: LoadBalancer
